package jcodingtime.java.verifier.parser;

/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int JCODINGTIME = 1;
  /** RegularExpression Id. */
  int INPUT = 2;
  /** RegularExpression Id. */
  int FPARAM = 3;
  /** RegularExpression Id. */
  int SPARAM = 4;
  /** RegularExpression Id. */
  int OUTPUT = 5;
  /** RegularExpression Id. */
  int RPARAM = 6;
  /** RegularExpression Id. */
  int LPAREN = 7;
  /** RegularExpression Id. */
  int RPAREN = 8;
  /** RegularExpression Id. */
  int LBRACE = 9;
  /** RegularExpression Id. */
  int RBRACE = 10;
  /** RegularExpression Id. */
  int LBRACKET = 11;
  /** RegularExpression Id. */
  int RBRACKET = 12;
  /** RegularExpression Id. */
  int SEMICOLON = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int DOT = 15;
  /** RegularExpression Id. */
  int AT = 16;
  /** RegularExpression Id. */
  int ASSIGN = 17;
  /** RegularExpression Id. */
  int LT = 18;
  /** RegularExpression Id. */
  int BANG = 19;
  /** RegularExpression Id. */
  int TILDE = 20;
  /** RegularExpression Id. */
  int HOOK = 21;
  /** RegularExpression Id. */
  int COLON = 22;
  /** RegularExpression Id. */
  int EQ = 23;
  /** RegularExpression Id. */
  int LE = 24;
  /** RegularExpression Id. */
  int GE = 25;
  /** RegularExpression Id. */
  int NE = 26;
  /** RegularExpression Id. */
  int SC_OR = 27;
  /** RegularExpression Id. */
  int SC_AND = 28;
  /** RegularExpression Id. */
  int INCR = 29;
  /** RegularExpression Id. */
  int DECR = 30;
  /** RegularExpression Id. */
  int PLUS = 31;
  /** RegularExpression Id. */
  int MINUS = 32;
  /** RegularExpression Id. */
  int STAR = 33;
  /** RegularExpression Id. */
  int SLASH = 34;
  /** RegularExpression Id. */
  int BIT_AND = 35;
  /** RegularExpression Id. */
  int BIT_OR = 36;
  /** RegularExpression Id. */
  int XOR = 37;
  /** RegularExpression Id. */
  int REM = 38;
  /** RegularExpression Id. */
  int LSHIFT = 39;
  /** RegularExpression Id. */
  int PLUSASSIGN = 40;
  /** RegularExpression Id. */
  int MINUSASSIGN = 41;
  /** RegularExpression Id. */
  int STARASSIGN = 42;
  /** RegularExpression Id. */
  int SLASHASSIGN = 43;
  /** RegularExpression Id. */
  int ANDASSIGN = 44;
  /** RegularExpression Id. */
  int ORASSIGN = 45;
  /** RegularExpression Id. */
  int XORASSIGN = 46;
  /** RegularExpression Id. */
  int REMASSIGN = 47;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 48;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 49;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 50;
  /** RegularExpression Id. */
  int ELLIPSIS = 51;
  /** RegularExpression Id. */
  int ARROW = 52;
  /** RegularExpression Id. */
  int DOUBLECOLON = 53;
  /** RegularExpression Id. */
  int DIGIT = 54;
  /** RegularExpression Id. */
  int INTEGER = 55;
  /** RegularExpression Id. */
  int REAL = 56;
  /** RegularExpression Id. */
  int ABSTRACT = 57;
  /** RegularExpression Id. */
  int ASSERT = 58;
  /** RegularExpression Id. */
  int BOOLEAN = 59;
  /** RegularExpression Id. */
  int BREAK = 60;
  /** RegularExpression Id. */
  int BYTE = 61;
  /** RegularExpression Id. */
  int CASE = 62;
  /** RegularExpression Id. */
  int CATCH = 63;
  /** RegularExpression Id. */
  int CHAR = 64;
  /** RegularExpression Id. */
  int CLASS = 65;
  /** RegularExpression Id. */
  int CONST = 66;
  /** RegularExpression Id. */
  int CONTINUE = 67;
  /** RegularExpression Id. */
  int _DEFAULT = 68;
  /** RegularExpression Id. */
  int DO = 69;
  /** RegularExpression Id. */
  int DOUBLE = 70;
  /** RegularExpression Id. */
  int ELSE = 71;
  /** RegularExpression Id. */
  int ENUM = 72;
  /** RegularExpression Id. */
  int EXTENDS = 73;
  /** RegularExpression Id. */
  int FALSE = 74;
  /** RegularExpression Id. */
  int FINAL = 75;
  /** RegularExpression Id. */
  int FINALLY = 76;
  /** RegularExpression Id. */
  int FLOAT = 77;
  /** RegularExpression Id. */
  int FOR = 78;
  /** RegularExpression Id. */
  int GOTO = 79;
  /** RegularExpression Id. */
  int IF = 80;
  /** RegularExpression Id. */
  int IMPLEMENTS = 81;
  /** RegularExpression Id. */
  int IMPORT = 82;
  /** RegularExpression Id. */
  int INSTANCEOF = 83;
  /** RegularExpression Id. */
  int INT = 84;
  /** RegularExpression Id. */
  int INTERFACE = 85;
  /** RegularExpression Id. */
  int LONG = 86;
  /** RegularExpression Id. */
  int NATIVE = 87;
  /** RegularExpression Id. */
  int NEW = 88;
  /** RegularExpression Id. */
  int NULL = 89;
  /** RegularExpression Id. */
  int PACKAGE = 90;
  /** RegularExpression Id. */
  int PRIVATE = 91;
  /** RegularExpression Id. */
  int PROTECTED = 92;
  /** RegularExpression Id. */
  int PUBLIC = 93;
  /** RegularExpression Id. */
  int RETURN = 94;
  /** RegularExpression Id. */
  int SHORT = 95;
  /** RegularExpression Id. */
  int STATIC = 96;
  /** RegularExpression Id. */
  int STRICTFP = 97;
  /** RegularExpression Id. */
  int SUPER = 98;
  /** RegularExpression Id. */
  int SWITCH = 99;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 100;
  /** RegularExpression Id. */
  int THIS = 101;
  /** RegularExpression Id. */
  int THROW = 102;
  /** RegularExpression Id. */
  int THROWS = 103;
  /** RegularExpression Id. */
  int TRANSIENT = 104;
  /** RegularExpression Id. */
  int TRUE = 105;
  /** RegularExpression Id. */
  int TRY = 106;
  /** RegularExpression Id. */
  int VOID = 107;
  /** RegularExpression Id. */
  int VOLATILE = 108;
  /** RegularExpression Id. */
  int WHILE = 109;
  /** RegularExpression Id. */
  int REQUIRES = 110;
  /** RegularExpression Id. */
  int TO = 111;
  /** RegularExpression Id. */
  int WITH = 112;
  /** RegularExpression Id. */
  int OPEN = 113;
  /** RegularExpression Id. */
  int OPENS = 114;
  /** RegularExpression Id. */
  int USES = 115;
  /** RegularExpression Id. */
  int MODULE = 116;
  /** RegularExpression Id. */
  int EXPORTS = 117;
  /** RegularExpression Id. */
  int PROVIDES = 118;
  /** RegularExpression Id. */
  int TRANSITIVE = 119;
  /** RegularExpression Id. */
  int CHARACTER = 120;
  /** RegularExpression Id. */
  int IDENTIFIER = 121;
  /** RegularExpression Id. */
  int LITERAL = 122;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"JCodingTime\"",
    "\"Input\"",
    "\"firstParam\"",
    "\"secondParam\"",
    "\"Output\"",
    "\"result\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\"->\"",
    "\"::\"",
    "<DIGIT>",
    "<INTEGER>",
    "<REAL>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"requires\"",
    "\"to\"",
    "\"with\"",
    "\"open\"",
    "\"opens\"",
    "\"uses\"",
    "\"module\"",
    "\"exports\"",
    "\"provides\"",
    "\"transitive\"",
    "<CHARACTER>",
    "<IDENTIFIER>",
    "<LITERAL>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
