package verifier.parser;

/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int JCODINGTIME = 1;
  /** RegularExpression Id. */
  int INPUT = 2;
  /** RegularExpression Id. */
  int OUTPUT = 3;
  /** RegularExpression Id. */
  int LPAREN = 4;
  /** RegularExpression Id. */
  int RPAREN = 5;
  /** RegularExpression Id. */
  int LBRACE = 6;
  /** RegularExpression Id. */
  int RBRACE = 7;
  /** RegularExpression Id. */
  int LBRACKET = 8;
  /** RegularExpression Id. */
  int RBRACKET = 9;
  /** RegularExpression Id. */
  int SEMICOLON = 10;
  /** RegularExpression Id. */
  int COMMA = 11;
  /** RegularExpression Id. */
  int DOT = 12;
  /** RegularExpression Id. */
  int AT = 13;
  /** RegularExpression Id. */
  int ASSIGN = 14;
  /** RegularExpression Id. */
  int LT = 15;
  /** RegularExpression Id. */
  int BANG = 16;
  /** RegularExpression Id. */
  int TILDE = 17;
  /** RegularExpression Id. */
  int HOOK = 18;
  /** RegularExpression Id. */
  int COLON = 19;
  /** RegularExpression Id. */
  int EQ = 20;
  /** RegularExpression Id. */
  int LE = 21;
  /** RegularExpression Id. */
  int GE = 22;
  /** RegularExpression Id. */
  int NE = 23;
  /** RegularExpression Id. */
  int SC_OR = 24;
  /** RegularExpression Id. */
  int SC_AND = 25;
  /** RegularExpression Id. */
  int INCR = 26;
  /** RegularExpression Id. */
  int DECR = 27;
  /** RegularExpression Id. */
  int PLUS = 28;
  /** RegularExpression Id. */
  int MINUS = 29;
  /** RegularExpression Id. */
  int STAR = 30;
  /** RegularExpression Id. */
  int SLASH = 31;
  /** RegularExpression Id. */
  int BIT_AND = 32;
  /** RegularExpression Id. */
  int BIT_OR = 33;
  /** RegularExpression Id. */
  int XOR = 34;
  /** RegularExpression Id. */
  int REM = 35;
  /** RegularExpression Id. */
  int LSHIFT = 36;
  /** RegularExpression Id. */
  int PLUSASSIGN = 37;
  /** RegularExpression Id. */
  int MINUSASSIGN = 38;
  /** RegularExpression Id. */
  int STARASSIGN = 39;
  /** RegularExpression Id. */
  int SLASHASSIGN = 40;
  /** RegularExpression Id. */
  int ANDASSIGN = 41;
  /** RegularExpression Id. */
  int ORASSIGN = 42;
  /** RegularExpression Id. */
  int XORASSIGN = 43;
  /** RegularExpression Id. */
  int REMASSIGN = 44;
  /** RegularExpression Id. */
  int LSHIFTASSIGN = 45;
  /** RegularExpression Id. */
  int RSIGNEDSHIFTASSIGN = 46;
  /** RegularExpression Id. */
  int RUNSIGNEDSHIFTASSIGN = 47;
  /** RegularExpression Id. */
  int ELLIPSIS = 48;
  /** RegularExpression Id. */
  int ARROW = 49;
  /** RegularExpression Id. */
  int DOUBLECOLON = 50;
  /** RegularExpression Id. */
  int DIGIT = 51;
  /** RegularExpression Id. */
  int INTEGER = 52;
  /** RegularExpression Id. */
  int REAL = 53;
  /** RegularExpression Id. */
  int ABSTRACT = 54;
  /** RegularExpression Id. */
  int ASSERT = 55;
  /** RegularExpression Id. */
  int BOOLEAN = 56;
  /** RegularExpression Id. */
  int BREAK = 57;
  /** RegularExpression Id. */
  int BYTE = 58;
  /** RegularExpression Id. */
  int CASE = 59;
  /** RegularExpression Id. */
  int CATCH = 60;
  /** RegularExpression Id. */
  int CHAR = 61;
  /** RegularExpression Id. */
  int CLASS = 62;
  /** RegularExpression Id. */
  int CONST = 63;
  /** RegularExpression Id. */
  int CONTINUE = 64;
  /** RegularExpression Id. */
  int _DEFAULT = 65;
  /** RegularExpression Id. */
  int DO = 66;
  /** RegularExpression Id. */
  int DOUBLE = 67;
  /** RegularExpression Id. */
  int ELSE = 68;
  /** RegularExpression Id. */
  int ENUM = 69;
  /** RegularExpression Id. */
  int EXTENDS = 70;
  /** RegularExpression Id. */
  int FALSE = 71;
  /** RegularExpression Id. */
  int FINAL = 72;
  /** RegularExpression Id. */
  int FINALLY = 73;
  /** RegularExpression Id. */
  int FLOAT = 74;
  /** RegularExpression Id. */
  int FOR = 75;
  /** RegularExpression Id. */
  int GOTO = 76;
  /** RegularExpression Id. */
  int IF = 77;
  /** RegularExpression Id. */
  int IMPLEMENTS = 78;
  /** RegularExpression Id. */
  int IMPORT = 79;
  /** RegularExpression Id. */
  int INSTANCEOF = 80;
  /** RegularExpression Id. */
  int INT = 81;
  /** RegularExpression Id. */
  int INTERFACE = 82;
  /** RegularExpression Id. */
  int LONG = 83;
  /** RegularExpression Id. */
  int NATIVE = 84;
  /** RegularExpression Id. */
  int NEW = 85;
  /** RegularExpression Id. */
  int NULL = 86;
  /** RegularExpression Id. */
  int PACKAGE = 87;
  /** RegularExpression Id. */
  int PRIVATE = 88;
  /** RegularExpression Id. */
  int PROTECTED = 89;
  /** RegularExpression Id. */
  int PUBLIC = 90;
  /** RegularExpression Id. */
  int RETURN = 91;
  /** RegularExpression Id. */
  int SHORT = 92;
  /** RegularExpression Id. */
  int STATIC = 93;
  /** RegularExpression Id. */
  int STRICTFP = 94;
  /** RegularExpression Id. */
  int SUPER = 95;
  /** RegularExpression Id. */
  int SWITCH = 96;
  /** RegularExpression Id. */
  int SYNCHRONIZED = 97;
  /** RegularExpression Id. */
  int THIS = 98;
  /** RegularExpression Id. */
  int THROW = 99;
  /** RegularExpression Id. */
  int THROWS = 100;
  /** RegularExpression Id. */
  int TRANSIENT = 101;
  /** RegularExpression Id. */
  int TRUE = 102;
  /** RegularExpression Id. */
  int TRY = 103;
  /** RegularExpression Id. */
  int VOID = 104;
  /** RegularExpression Id. */
  int VOLATILE = 105;
  /** RegularExpression Id. */
  int WHILE = 106;
  /** RegularExpression Id. */
  int REQUIRES = 107;
  /** RegularExpression Id. */
  int TO = 108;
  /** RegularExpression Id. */
  int WITH = 109;
  /** RegularExpression Id. */
  int OPEN = 110;
  /** RegularExpression Id. */
  int OPENS = 111;
  /** RegularExpression Id. */
  int USES = 112;
  /** RegularExpression Id. */
  int MODULE = 113;
  /** RegularExpression Id. */
  int EXPORTS = 114;
  /** RegularExpression Id. */
  int PROVIDES = 115;
  /** RegularExpression Id. */
  int TRANSITIVE = 116;
  /** RegularExpression Id. */
  int CHARACTER = 117;
  /** RegularExpression Id. */
  int IDENTIFIER = 118;
  /** RegularExpression Id. */
  int LITERAL = 119;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"jcodingtime\"",
    "\"input\"",
    "\"output\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"@\"",
    "\"=\"",
    "\"<\"",
    "\"!\"",
    "\"~\"",
    "\"?\"",
    "\":\"",
    "\"==\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"||\"",
    "\"&&\"",
    "\"++\"",
    "\"--\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"&\"",
    "\"|\"",
    "\"^\"",
    "\"%\"",
    "\"<<\"",
    "\"+=\"",
    "\"-=\"",
    "\"*=\"",
    "\"/=\"",
    "\"&=\"",
    "\"|=\"",
    "\"^=\"",
    "\"%=\"",
    "\"<<=\"",
    "\">>=\"",
    "\">>>=\"",
    "\"...\"",
    "\"->\"",
    "\"::\"",
    "<DIGIT>",
    "<INTEGER>",
    "<REAL>",
    "\"abstract\"",
    "\"assert\"",
    "\"boolean\"",
    "\"break\"",
    "\"byte\"",
    "\"case\"",
    "\"catch\"",
    "\"char\"",
    "\"class\"",
    "\"const\"",
    "\"continue\"",
    "\"default\"",
    "\"do\"",
    "\"double\"",
    "\"else\"",
    "\"enum\"",
    "\"extends\"",
    "\"false\"",
    "\"final\"",
    "\"finally\"",
    "\"float\"",
    "\"for\"",
    "\"goto\"",
    "\"if\"",
    "\"implements\"",
    "\"import\"",
    "\"instanceof\"",
    "\"int\"",
    "\"interface\"",
    "\"long\"",
    "\"native\"",
    "\"new\"",
    "\"null\"",
    "\"package\"",
    "\"private\"",
    "\"protected\"",
    "\"public\"",
    "\"return\"",
    "\"short\"",
    "\"static\"",
    "\"strictfp\"",
    "\"super\"",
    "\"switch\"",
    "\"synchronized\"",
    "\"this\"",
    "\"throw\"",
    "\"throws\"",
    "\"transient\"",
    "\"true\"",
    "\"try\"",
    "\"void\"",
    "\"volatile\"",
    "\"while\"",
    "\"requires\"",
    "\"to\"",
    "\"with\"",
    "\"open\"",
    "\"opens\"",
    "\"uses\"",
    "\"module\"",
    "\"exports\"",
    "\"provides\"",
    "\"transitive\"",
    "<CHARACTER>",
    "<IDENTIFIER>",
    "<LITERAL>",
    "\" \"",
    "\"\\r\\n\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
  };

}
